# Generated by Django 4.2.7 on 2023-11-30 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название агентства')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('price', models.CharField(max_length=5, verbose_name='Цена')),
                ('people', models.CharField(max_length=4, verbose_name='Количество человек')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Агентство',
                'verbose_name_plural': 'Агентства',
            },
        ),
        migrations.CreateModel(
            name='categorieslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('email', models.CharField(max_length=40, verbose_name='Почта')),
                ('question', models.CharField(max_length=30, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
        migrations.CreateModel(
            name='plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название тарифа')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название услги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название решения')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
            },
        ),
        migrations.CreateModel(
            name='solutionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plans', verbose_name='Тариф')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.services', verbose_name='Услуга')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solutions', verbose_name='Решение')),
            ],
            options={
                'verbose_name': 'Услуга в тарифе',
                'verbose_name_plural': 'Услуги в тарифах',
            },
        ),
        migrations.CreateModel(
            name='pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=6, verbose_name='Стоимость услуги')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='агентство')),
            ],
            options={
                'verbose_name': 'Прайс лист',
                'verbose_name_plural': 'Прайс листы',
            },
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='Агентство')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.solutions', verbose_name='Решение')),
            ],
            options={
                'verbose_name': 'Галлерея',
                'verbose_name_plural': 'Галлерея',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='агентство')),
                ('categorieslist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorieslist', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Категория агентства',
                'verbose_name_plural': 'Категории агентств',
            },
        ),
        migrations.CreateModel(
            name='book_solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField(default='', verbose_name='Дата')),
                ('book_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.place', verbose_name='Площадка')),
                ('solutionPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plans', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
