# Generated by Django 4.2.7 on 2023-11-26 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название агентства')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('price', models.CharField(max_length=5, verbose_name='Цена')),
                ('people', models.CharField(max_length=4, verbose_name='Количество человек')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='categorieslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('email', models.CharField(max_length=40, verbose_name='Почта')),
                ('question', models.CharField(max_length=30, verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=6, verbose_name='Стоимость услуги')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='агентство')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='агентство')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='агентство')),
                ('categorieslist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorieslist', verbose_name='категория')),
            ],
        ),
    ]
