# Generated by Django 4.2.6 on 2023-11-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название агентства')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('price', models.CharField(max_length=5, verbose_name='Цена')),
                ('people', models.CharField(max_length=4, verbose_name='Количество человек')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
            ],
        ),
    ]
