# Generated by Django 4.2.7 on 2023-11-26 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название решения')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='Агентство'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.solutions', verbose_name='Решение'),
        ),
    ]
