# Generated by Django 4.2.6 on 2023-11-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='description',
            field=models.CharField(max_length=600, verbose_name='Описание'),
        ),
    ]
