# Generated by Django 4.2.7 on 2023-11-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_solution',
            old_name='book_date',
            new_name='date',
        ),
    ]
