# Generated by Django 4.2.7 on 2023-11-26 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_solutions_alter_gallery_agent_gallery_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название тарифа')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название услги')),
            ],
        ),
        migrations.CreateModel(
            name='solutionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plans', verbose_name='Тариф')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.services', verbose_name='Услуга')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solutions', verbose_name='Решение')),
            ],
        ),
    ]
