# Generated by Django 4.2.7 on 2023-11-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_book_date_book_solution_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_solution',
            old_name='date',
            new_name='book_date',
        ),
    ]
