# Generated by Django 4.2.7 on 2023-11-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_agency_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=6, verbose_name='Стоимость услуги')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='Агентство')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='Агентство')),
            ],
        ),
    ]
