# Generated by Django 4.2.7 on 2023-11-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pricelist_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.CharField(default=1, max_length=200, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
