# Generated by Django 4.2.7 on 2023-12-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_date_book_solution_book_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_solution',
            old_name='solutionPlan',
            new_name='plan',
        ),
        migrations.AddField(
            model_name='book_solution',
            name='solution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.solutions', verbose_name='Решение'),
            preserve_default=False,
        ),
    ]
