# Generated by Django 4.2.7 on 2023-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_solutionplan_book_solution_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_solution',
            name='book_date',
            field=models.DateField(default='', unique=True, verbose_name='Дата'),
        ),
    ]
