# Generated by Django 4.2.7 on 2023-11-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gallery_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='agent',
        ),
        migrations.AddField(
            model_name='agency',
            name='Gallery',
            field=models.ManyToManyField(null=True, to='main.gallery'),
        ),
        migrations.AddField(
            model_name='agency',
            name='Pricelist',
            field=models.ManyToManyField(null=True, to='main.pricelist'),
        ),
    ]
