# Generated by Django 4.2.7 on 2023-11-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_gallery_agent_remove_pricelist_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='Pricelist',
        ),
        migrations.AddField(
            model_name='gallery',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='агентство'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='агентство'),
            preserve_default=False,
        ),
    ]
