# Generated by Django 4.2.7 on 2023-12-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_solution_book_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название подрядчика')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('type', models.CharField(max_length=40, verbose_name='Тип мероприятий')),
                ('experience', models.CharField(max_length=2, verbose_name='Опыт работы')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
            },
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='агентство'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='contractors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contractor', verbose_name='Подрядчик'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='contractors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contractor', verbose_name='Подрядчик'),
        ),
    ]
