# Generated by Django 4.2.7 on 2023-11-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_agency_gallery_remove_agency_pricelist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Категория')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='агентство')),
            ],
        ),
    ]
