# Generated by Django 4.2.7 on 2023-11-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorieslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency', verbose_name='агентство')),
                ('categorieslist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorieslist', verbose_name='категория')),
            ],
        ),
        migrations.DeleteModel(
            name='categories',
        ),
    ]
