# Generated by Django 4.2.7 on 2023-12-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contractor_alter_pricelist_agent_gallery_contractors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название услги'),
        ),
    ]
