# Generated by Django 4.2.7 on 2023-12-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_services_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название решения'),
        ),
    ]
