# Generated by Django 4.2.7 on 2023-11-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_categorieslist_category_delete_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('email', models.CharField(max_length=40, verbose_name='Почта')),
                ('question', models.CharField(max_length=30, verbose_name='Вопрос')),
            ],
        ),
    ]
